name: mydotnetproject
 
on:
  push:
    branches:
      - develop
 
jobs:
  dotnet-publish:
    runs-on: 'ubuntu-latest'
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.100'
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3
 
        with:
          args: >
             -Dsonar.organization=noporganisation
             -Dsonar.projectKey=noporganisation_nop-commerce
        env:
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              mysonar_url: https://sonarcloud.io
      - name: Publish project
        run: dotnet publish -c release src/Presentation/Nop.Web/Nop.Web.csproj -o dheeraj
      # AWS CONFIGURE
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-seceret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        # build and push docker image
      - name: Build Docker image
        env:
          ECR_REGISTRY: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 542833615945.dkr.ecr.ap-south-1.amazonaws.com
          ECR_REPOSITORY: ecr/nopcommerce
          IMAGE_TAG: latest
        run: |
          docker build -t ecr/nopcommerce .
          docker tag ecr/nopcommerce:latest 542833615945.dkr.ecr.ap-south-1.amazonaws.com/ecr/nopcommerce:latest
          docker push 542833615945.dkr.ecr.ap-south-1.amazonaws.com/ecr/nopcommerce:latest